source 'http://rubygems.org'

gem 'rails', '3.0.9'
gem 'mysql2', '< 0.3'
gem 'jquery-rails'
gem 'omniauth', '~> 0.3.2'
gem 'oauth'
gem 'oa-openid', :require => 'omniauth/openid' 
gem 'haml'
gem 'compass', '0.11.5'
gem 'carrierwave'
gem 'rmagick'
gem 'spreadsheet'
gem 'pdfkit'
gem 'cancan'
