assets_path: "/public/assets/"
admin_email: "enrique.turcott@cimav.edu.mx" #developer
interships_cards_email: "biblioteca@cimav.edu.mx" #biblioteca
school_services1: "ariane.paz@cimav.edu.mx" #Ariane
school_services2: "rocio.baeza@cimav.edu.mx" #Rocio

